### ISSUE TITLE
Event Subscriptions / slack bot

### ISSUE THREAD

**Issue by fedaaZeyad** [slackapi/Slack-Ruby-Onboarding-Tutorial#3]
I'm trying to build a bot using slack api 
![errore](https://user-images.githubusercontent.com/38032684/38350394-c4dabf3e-38b3-11e8-977a-ab1ea1ef4227.PNG)

when I'm adding the redirect URL I got this error 
how can I fix this error ???

**Comment by Roach** [comment]
@fedaaZeyad please join the Bot Developer hangout so we can help you outside of Github issues. 

https://community.botkit.ai/

I'm on there as @roach.
